package in.app;

import java.io.IOException;
import java.io.PrintWriter;

import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet(name = "secondServlet", urlPatterns = {"/second"})
public class SecondServlet extends HttpServlet {
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse res) throws IOException{
        res.setContentType("text/html");

        PrintWriter out = res.getWriter();

        out.println("""
                    <div style="border: 2px solid black; padding: 10px; margin: 10px;">
                        <h3>Second Servlet Output</h3>
                        <p>This content is generated by SecondServlet.</p>
                    </div>
                """);

        out.flush();
    }
}
